import React from 'react';
import Header from './Header';
import Footer from './Footer';


class PrivacyPolicy extends React.Component {
    constructor(props) {
        super(props);
        this.state = {

        }
    }


    render() {
        return (
            <>
                <Header />
                <div>

                    <section class="bradcrumb-area">
                        <div class="container">
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="bradcrumb-main">
                                        <div class="bradcrumb-title">
                                            <h1>Privacy Policy</h1>
                                        </div>
                                        <div class="bradcrumb-right clearfix">
                                            <ul class="clearfix">
                                                <li><a href="index.html">Home</a></li>
                                                <li>Privacy Policy</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <section class="privacy-policy-area page-paddings">
                        <div class="container">
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="user-policy-main">
                                        <div class="user-policy-box">
                                            <p class="theme-description">This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.</p>
                                            <p class="theme-description">We use your data to provide and improve the Service. By using the Service, You agree to the collection and use of information following this Privacy Policy.</p>
                                            <h3 class="theme-title">Definitions</h3>
                                            <p class="theme-description">By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
                                            <h3 class="theme-title">For this Privacy Policy:</h3>
                                            <p class="theme-description">Account means a unique account created for you to access our Service or parts of our Service.</p>
                                            <p class="theme-description">Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to NFT – Marketplace.</p>
                                            <p class="theme-description">Cookies are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</p>
                                            <p class="theme-description">Device means any device that can access the Service such as a computer, a cell phone, or a digital tablet.</p>
                                            <p class="theme-description">Personal Data is any information that relates to an identified or identifiable individual.</p>
                                            <p class="theme-description">Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</p>
                                            <p class="theme-description">Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                                            <h2>Collecting and Using Your Personal Data</h2>
                                            <div class="privacy-left-box">
                                                <h3 class="theme-title">Personal Data</h3>
                                                <p class="theme-description">While using Our Service, We may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally, identifiable information may include.</p>
                                                <ul>
                                                    <li>Email address</li>
                                                    <li>First name and Username</li>
                                                    <li>Usage Data</li>
                                                </ul>
                                                <h3 class="theme-title">Usage Data</h3>
                                                <p class="theme-description">Usage Data has collected automatically when using the Service.</p>
                                                <p class="theme-description">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                                                <p class="theme-description">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                                                <p class="theme-description">We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.</p>
                                                <h3 class="theme-title">Cookies or Browser Cookies</h3>
                                                <p class="theme-description">A cookie is a small file placed on Your Device. You can instruct your browser to refuse all Cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, You may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it will refuse cookies, our Service may use Cookies.</p>
                                                <h3 class="theme-title">Privacy Policies For Advertising Partners</h3>
                                                <p class="theme-description">You may consult this list to find the Privacy Policy for each of the advertising partners of NFT - Marketplace. Third-party ad servers or ad networks use technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>
                                                <h3 class="theme-title">Retention of Your Personal Data</h3>
                                                <p class="theme-description">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                                                <p class="theme-description">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of Our Service, or we are legally obligated to retain this data for longer periods.</p>
                                                <h3 class="theme-title">Security of Your Personal Data</h3>
                                                <p class="theme-description">The security of Your Personal Data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                                                <p class="theme-description">If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.</p>
                                                <p class="theme-description">We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
                                                <p class="theme-description">We will let you know via email and/or a prominent notice on Our Service before the change becomes effective and update the "Last Updated" date at the top of this Privacy Policy.</p>
                                                <p class="theme-description">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>


                </div>
                <Footer />
            </>
        )
    }
};


export default PrivacyPolicy;